import redis
import threading
import json
from flask import Flask

app = Flask(__name__)
r = redis.Redis(host='redis', port=6379, db=0)
p = r.pubsub()

def listen_for_messages():
    p.subscribe('docs_channel')
    print("Listening for messages on 'docs_channel'...")

    for message in p.listen():
        if message['type'] == 'message':
            received_payload = json.loads(message['data'].decode('utf-8'))
            plantuml_code = received_payload['plantuml_code']
            original_text = received_payload['original_text']

            print(f"Final agent received PlantUML code. Creating documentation...")

            # 마크다운 문서 생성
            markdown_content = f"# Infrastructure Design Document\n\n"
            markdown_content += f"## User Request\n\n"
            markdown_content += f"**Original request:** {original_text}\n\n"
            markdown_content += f"## Architecture Diagram (PlantUML)\n\n"
            markdown_content += f"```plantuml\n{plantuml_code}```\n\n"
            markdown_content += f"This document was automatically generated by the agent system."

            # 파일로 저장
            with open("output/design_document.md", "w") as f:
                f.write(markdown_content)

            print("Documentation saved to design_document.md!")

threading.Thread(target=listen_for_messages, daemon=True).start()

@app.route('/')
def status():
    return 'agent_docs is running and listening for messages!'

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)